### ISSUE TITLE
Synchronize slider and description

### ISSUE THREAD

**Issue by Emerson452** [Popoyoko/les-ecuries#67]

**Comment by Emerson452** [comment]
Resolved by this [pr](https://github.com/Popoyoko/les-ecuries/pull/68)

**Comment by LouiFi** [comment]
We still have an issue with this slider, sometimes no description is associated with the image.

I already merged the lasts changes so please create a new branch.
